### ISSUE TITLE
Server no response after inserting illegal localStorage cart quantity

### ISSUE THREAD

**Issue by s1155033765** [ierg4210/shop57#1]
Just change the quantity = -1, then checkout

Consequence

Server did not response correctly

Possible fix: PayPal gives error, but server did not handle this error correctly

Images of Proof:

http://i218.photobucket.com/albums/cc176/William_AOE/IERG4210/store57%20illegal%20cart.png

http://i218.photobucket.com/albums/cc176/William_AOE/IERG4210/store57%20paypal%20gateway%20timeout.png

**Comment by aegix** [comment]
Fixed, but I do no agree that this is a security issue because no vulnerabilities are available because of the bug

**Comment by s1155033765** [comment]
Didn't said anything about vul., but bug...
